import { NextResponse } from 'next/server';
import { supabaseAdmin } from '../../../lib/supabase-server';
import { getSession } from '../../../lib/auth';

// ---------------------------------------------------------------------------
// Corporate Premium RFQ
//   POST /api/corp-premium  — a client submits a corporate / long-term request
//   GET  /api/corp-premium  — client sees own requests, admin sees all
//
// Two front-ends post here:
//   /corp-premium      — multi-location form (locations[])
//   /client/rfq        — long-term contract form (regions as free text)
// Either shape is accepted; at least one of them must describe where the work is.
//
// request_number is generated by a database trigger (CPR-YYYY-NNN), so it is
// deliberately not set here.
// ---------------------------------------------------------------------------

const VALID_LOCATION_TYPES = ['pickup', 'delivery'];
const MAX_LOCATIONS = 50;
const MAX_ATTACHMENTS = 20;

const str = (v, max) => {
  if (typeof v !== 'string') return null;
  const s = v.trim();
  if (!s) return null;
  return s.slice(0, max);
};

const num = (v) => {
  if (v === null || v === undefined || v === '') return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
};

const strArray = (v, max = 20) =>
  Array.isArray(v) ? v.filter(x => typeof x === 'string' && x.trim()).slice(0, max).map(x => x.trim().slice(0, 100)) : [];

// The region / vehicle columns are text[]. Accept an array or a comma-separated
// string so both front-ends can post the same endpoint.
const regionArray = (v) => {
  if (Array.isArray(v)) return strArray(v);
  if (typeof v === 'string') return strArray(v.split(','));
  return [];
};

// Keep only the fields we expect, so a malformed client cannot write junk.
function cleanLocations(raw) {
  if (!Array.isArray(raw)) return [];
  return raw
    .filter(l => l && typeof l === 'object')
    .slice(0, MAX_LOCATIONS)
    .map(l => ({
      type: VALID_LOCATION_TYPES.includes(l.type) ? l.type : 'delivery',
      address: str(l.address, 300) || '',
      contact: str(l.contact, 100) || '',
      phone: str(l.phone, 40) || '',
    }))
    .filter(l => l.address);
}

// Accepts either ["https://..."] or [{ name, url, size, type }].
function cleanAttachments(raw) {
  if (!Array.isArray(raw)) return [];
  return raw
    .slice(0, MAX_ATTACHMENTS)
    .map(a => {
      if (typeof a === 'string') return { name: 'file', url: str(a, 1000) || '', size: null, type: '' };
      if (a && typeof a === 'object') {
        return {
          name: str(a.name, 200) || 'file',
          url: str(a.url, 1000) || '',
          size: num(a.size),
          type: str(a.type, 100) || '',
        };
      }
      return { name: 'file', url: '', size: null, type: '' };
    })
    .filter(a => a.url.startsWith('http'));
}

export async function POST(request) {
  const session = getSession(request);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  if (session.role !== 'client') {
    return NextResponse.json({ error: 'Only client accounts can submit a corporate request' }, { status: 403 });
  }

  try {
    const body = await request.json();

    const title = str(body.title, 200);
    if (!title) return NextResponse.json({ error: 'Project title is required' }, { status: 400 });

    if (body.nda_accepted !== true) {
      return NextResponse.json({ error: 'The NDA must be accepted before submitting' }, { status: 400 });
    }

    const locations = cleanLocations(body.locations);
    const pickupRegions = regionArray(body.pickup_regions);
    const deliveryRegions = regionArray(body.delivery_regions);

    // The multi-location form gives addresses; the RFQ form gives regions.
    // One of the two has to be present.
    if (locations.length === 0 && pickupRegions.length === 0 && deliveryRegions.length === 0) {
      return NextResponse.json(
        { error: 'Add at least one location, or a pickup / delivery region' },
        { status: 400 }
      );
    }

    const row = {
      client_id: session.userId,
      title,
      description: str(body.description, 5000),
      start_date: str(body.start_date, 10),
      end_date: str(body.end_date, 10),
      estimated_budget: num(body.estimated_budget),
      locations,
      vehicle_modes: strArray(body.vehicle_modes),
      special_requirements: str(body.special_requirements, 3000),
      // the form field is `certifications`; the column is `certifications_required`
      certifications_required: strArray(body.certifications ?? body.certifications_required),
      min_fleet_size: num(body.min_fleet_size) ?? 1,
      min_rating: num(body.min_rating) ?? 4.5,
      nda_accepted: true,
      attachments: cleanAttachments(body.attachments),
      contract_duration: num(body.contract_duration) ?? 3,
      estimated_volume: str(body.estimated_volume, 200),
      pickup_regions: pickupRegions,
      delivery_regions: deliveryRegions,
      vehicle_types: regionArray(body.vehicle_types),
      status: 'submitted',
    };

    const { data, error } = await supabaseAdmin
      .from('corp_premium_requests')
      .insert([row])
      .select('id, request_number, title, status, created_at')
      .single();

    if (error) {
      console.error('[CORP-PREMIUM] insert error:', error.message);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    // Tell the admins. Never let a notification failure lose the request.
    try {
      const { data: admins } = await supabaseAdmin
        .from('express_users')
        .select('id')
        .eq('role', 'admin');

      if (admins?.length) {
        const pickups = locations.filter(l => l.type === 'pickup').length;
        const drops = locations.filter(l => l.type === 'delivery').length;
        const summary = locations.length
          ? `${pickups} pickup(s), ${drops} delivery location(s)`
          : `${row.contract_duration}-month contract${row.estimated_volume ? ` — ${row.estimated_volume}` : ''}`;

        await supabaseAdmin.from('express_notifications').insert(
          admins.map(a => ({
            user_id: a.id,
            type: 'corp_premium_request',
            title: `New corporate request: ${title.slice(0, 60)}`,
            body: `${data.request_number || 'RFQ'} — ${summary}`,
            reference_id: data.id,
            is_read: false,
          }))
        );
      }
    } catch (notifErr) {
      console.error('[CORP-PREMIUM] notification error:', notifErr?.message);
    }

    return NextResponse.json({ data });
  } catch (err) {
    console.error('[CORP-PREMIUM] POST error:', err);
    return NextResponse.json({ error: 'Server error' }, { status: 500 });
  }
}

export async function GET(request) {
  const session = getSession(request);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  try {
    const { searchParams } = new URL(request.url);
    const status = searchParams.get('status');

    let query = supabaseAdmin
      .from('corp_premium_requests')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(200);

    // Admins see everything; a client sees only their own.
    if (session.role !== 'admin') query = query.eq('client_id', session.userId);
    if (status) query = query.eq('status', status);

    const { data, error } = await query;
    if (error) {
      console.error('[CORP-PREMIUM] GET error:', error.message);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    const rows = data || [];

    // Attach the client record separately rather than relying on a PostgREST
    // embed - the foreign key is not guaranteed to exist in the live database.
    const clientIds = [...new Set(rows.map(r => r.client_id).filter(Boolean))];
    let byId = {};
    if (clientIds.length) {
      const { data: clients, error: clientErr } = await supabaseAdmin
        .from('express_users')
        .select('id, contact_name, company_name, email, phone')
        .in('id', clientIds);
      if (clientErr) console.error('[CORP-PREMIUM] client lookup error:', clientErr.message);
      for (const c of clients || []) byId[c.id] = c;
    }

    return NextResponse.json({
      data: rows.map(r => ({ ...r, client: byId[r.client_id] || null })),
    });
  } catch (err) {
    console.error('[CORP-PREMIUM] GET error:', err);
    return NextResponse.json({ error: 'Server error' }, { status: 500 });
  }
}
